/*
 * Copyright 2025 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.recipe.picnic.internal;

import org.jspecify.annotations.NullMarked;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.jar.JarFile;
import java.util.zip.ZipEntry;

import static java.util.Collections.emptyList;
import static java.util.stream.Collectors.toList;

@NullMarked
public class GeneratePicnicAggregation {

    static final String PACKAGE_PATH = "tech/picnic/errorprone/refasterrules/";
    static final String RECIPES_SUFFIX = "RulesRecipes.class";

    public static void main(String[] args) throws IOException {
        if (args.length < 1) {
            System.out.println("Usage: java GeneratePicnicAggregation <path to picnic.yml>");
            return;
        }

        Path target = Path.of(args[0]);
        List<String> recipes = findRulesRecipesOnClasspath();
        if (recipes.isEmpty()) {
            throw new IllegalStateException(
              "No Picnic *RulesRecipes classes found on the classpath; ensure error-prone-contrib:recipes is a dependency.");
        }

        Files.writeString(target, renderYaml(recipes));
        System.out.printf("Wrote %d Picnic Refaster rule collections to %s%n", recipes.size(), target.toAbsolutePath());
    }

    public static List<String> findRulesRecipesOnClasspath() throws IOException {
        for (String entry : System.getProperty("java.class.path").split(File.pathSeparator)) {
            if (!entry.endsWith(".jar") || !entry.contains("error-prone-contrib")) {
                continue;
            }
            try (JarFile jar = new JarFile(entry)) {
                List<String> classes = jar.stream()
                  .map(ZipEntry::getName)
                  .filter(n -> n.startsWith(PACKAGE_PATH) && n.endsWith(RECIPES_SUFFIX) && !n.contains("$"))
                  .map(n -> n.substring(0, n.length() - ".class".length()).replace('/', '.'))
                  .sorted()
                  .collect(toList());
                if (!classes.isEmpty()) {
                    return classes;
                }
            }
        }
        return emptyList();
    }

    static final String GENERATED_MARKER = "# This file is auto-generated by running `./gradlew generatePicnicAggregation`.";

    public static String renderYaml(List<String> recipes) {
        StringBuilder sb = new StringBuilder();
        sb.append(GENERATED_MARKER).append('\n');
        sb.append("""
                ---
                type: specs.openrewrite.org/v1beta/recipe
                name: tech.picnic.errorprone.refasterrules.AllRefasterRules
                displayName: All Picnic Refaster rules
                description: Collection of all Refaster rules from Picnic's error-prone-contrib project.
                recipeList:
                """);
        for (String recipe : recipes) {
            sb.append("  - ").append(recipe).append('\n');
        }
        return sb.toString();
    }
}
